name: plantgo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management - BLoC
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.7.0
  injectable: ^2.4.4
  
  # Network & HTTP
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  
  # Firebase dependencies
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.6
  cloud_firestore: ^4.13.6
  
  # Map and location dependencies
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^10.1.0
  
  # Image handling dependencies
  image_picker: ^1.0.4
  image: ^4.1.3
  path_provider: ^2.1.1
  
  # UI dependencies
  flutter_typeahead: ^5.0.1
  
  # Utilities
  dartz: ^0.10.1
  freezed_annotation: ^2.4.4
  device_info_plus: ^10.0.0
  flutter_web_auth_2: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  
  # Code generation
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  retrofit_generator: ^8.2.0
  json_serializable: ^6.8.0
  freezed: ^2.5.7

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/riddles/
    - assets/background/
    - assets/mascot/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
