name: plantgo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase dependencies
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  
  # Map and location dependencies
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^10.1.0
  
  # Image handling dependencies
  image_picker: ^1.0.4
  image: ^4.1.3
  path_provider: ^2.1.1
  
  # UI dependencies
  flutter_typeahead: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/riddles/
    - assets/background/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
